# Generated by Django 3.0.4 on 2021-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booker',
            new_name='booked_by',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='gsm',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
