# Generated by Django 3.0.4 on 2021-01-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20210119_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gsm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
