# Generated by Django 3.0.4 on 2021-01-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20210119_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Visitor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='leave_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='settle_date',
            field=models.DateTimeField(),
        ),
    ]
