# Generated by Django 3.0.4 on 2021-01-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210120_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_visitors',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
