# Generated by Django 3.0.4 on 2021-01-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_booking_number_of_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=50, unique=True)),
                ('meta_value', models.BooleanField()),
            ],
            options={
                'db_table': 'charta_system_setting',
            },
        ),
        migrations.CreateModel(
            name='RoomVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Room')),
                ('visitor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Visitor')),
            ],
            options={
                'db_table': 'charta_room_visitor',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_date', models.DateTimeField()),
                ('leave_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Booking')),
                ('reserved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Visitor')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Room')),
            ],
            options={
                'db_table': 'charta_reservation',
            },
        ),
    ]
