# Generated by Django 3.0.4 on 2021-01-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_reservation_roomvisitor_systemsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
